[29기 이강일] 회원가입 및 로그인 구현
wecode-bootcamp-korea/29-1st-Apocalypse-backend pull request #4
Opened 2022-01-26 06:40 UTC by kangil2

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [x] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 회원 가입 및 로그인

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 회원 가입 및 로그인 기능 구현
- 회원 가입시 유효성 검사( 이메일, 비밀번호 형식)
- 로그인 시 유효성 검사 ( 이메일, 비밀번호 형식)
- 회원 가입 및 로그인시 유효성 검사에 통과하지 못할 경우 에러 반환
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-01-26 07:53 UTC, lordmyshepherd requested changes
👍🏻

2022-01-26 07:53 UTC, lordmyshepherd commented on users/views.py
> +            user            = User.objects.get(email = email)
위에 Signup에서는 email, password input을 검증하는 로직이 있는데 로그인 할때는 검증 안해도 되나요??

```python
            if not re.match(r'^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$', email):
                return JsonResponse({'message' : 'INVALID EMAIL'},       status = 400)
            if not re.match(r'^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$', password):
                return JsonResponse({'message' : 'INVALID PASSWORD'},    status = 400)
```

2022-01-26 09:00 UTC, kangil2 commented on users/views.py
> +            user            = User.objects.get(email = email)
로그인 시 DB상의 데이터와 일치 하는지 하지않는지 검증만 하면 되게끔 사이트를 토대로 구현했습니다.

2022-01-26 09:03 UTC, lordmyshepherd requested changes

2022-01-26 09:03 UTC, lordmyshepherd commented on users/views.py
> +            user            = User.objects.get(email = email)
잘못된 input이 들어오는 경우 굳이 DB를 호출하지 않도록 View에서 email을 한번 더 검증하면 좋지 않을까요?

2022-01-26 09:13 UTC, kangil2 commented on users/views.py
> +            user            = User.objects.get(email = email)
리뷰 반영 후 다시 올렸습니다~

2022-01-27 05:17 UTC, lordmyshepherd commented
구두로 말씀드린 내용 반영해서 push 해주시면 감사하겠습니다-!

2022-01-27 06:11 UTC, kangil2 commented
설명 해주신 내용 반영해서 push 완료했습니다

2022-01-27 07:02 UTC, lordmyshepherd requested changes

2022-01-27 07:02 UTC, lordmyshepherd commented on users/views.py
> +            user            = User.objects.get(email = email)
잘 고쳐주셨습니다-! 한가지 피드백만 더 드리자면,

1. REGEX_EMAIL, REGEX_PASSWORD 규칙은 data로 볼 수 있습니다.
2. Email을 검증한다.(`re.match(REGEX_EMAIL, email)`), 비밀번호를 검증한다.(`re.match(REGEX_PASSWORD, password)`)는 Action(행동)으로 볼 수 있습니다.

`class = data + action`이라고 말씀드렸었죠?!
그래서 지금 같은 구조를 class로 만들게 되면 if, elif가 필요 없이 구조적으로 코드를 작성할 수 있습니다.

```python
REGEX_EMAIL    = r'^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
REGEX_PASSWORD = r'^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'
```


```python
if not re.match(REGEX_EMAIL, email):
    return JsonResponse({'message' : 'INVALID EMAIL'},     status = 400)
elif not re.match(REGEX_PASSWORD, password):
    return JsonResponse({'message' : 'INVALID PASSWORD1'}, status = 400)
```

결로적으로 말씀드리면, `SignInView`, `SignupView`에서 공통되는 data와 action 부분을 class로 구현해보시면 좋을 것 같습니다.

2022-01-27 07:11 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-01-27 07:11 UTC, merged