[Add/Modify] 메인페이지 한정판/신상품 출력 , 모델링 수정
wecode-bootcamp-korea/29-1st-Apocalypse-backend pull request #6
Opened 2022-01-27 09:31 UTC by aerialslash0422

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [x] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
<br />

메인페이지 특별상품 출력/모델링 수정
## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

<br />

![스크린샷, 2022-01-26 18-16-05](https://user-images.githubusercontent.com/33915211/151330813-2beaea4f-950e-42e8-94fb-36f20909f036.png)
![스크린샷, 2022-01-26 18-16-17](https://user-images.githubusercontent.com/33915211/151330828-152ed1c2-41c9-4fa1-8411-557f9cb84320.png)
![스크린샷, 2022-01-26 18-16-30](https://user-images.githubusercontent.com/33915211/151330845-2b52d2bc-e917-4725-b912-5a51555194e6.png)

1. 상품명에 '리미티드' 가 포함된 한정판(프로모션) 상품 이미지 출력
이미지는 상품의 첫번째 이미지만 출력
2. 3번 스크린샷에서 보이는 '완벽한 선물'을 신상품으로 대체하였습니다.
상품을 신상품순으로 정렬한 뒤 앞에서 5개만 아이디/한국명/영어명/가격/이미지 출력
이미지는 상품의 첫번째 이미지만 출력 
3. 모델링 수정(서브카테고리 이미지 필드 추가)

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
<br />
1. 결과가 비슷한 views는 하나로 묶어야 된 점을 알게 되었습니다.

2. order_by를 통한 ordering과 lt gt lte gte 옵션을 알게 되었습니다.

## :: 기타 질문 및 특이 사항
<br />
해당 기능에 prefetch_related와 select_related를 적용할 수 있는지 궁금합니다.

2022-01-27 11:02 UTC, lordmyshepherd requested changes

2022-01-27 11:02 UTC, lordmyshepherd commented on products/views.py
> +class MainPageProductList(View):
페이지 기준으로 엔드포인트를 만드시면 안됩니다.
이런 방식으로 엔드포인트를 구현하게 되면, 매번 client에서 새로운 페이지를 만들때마다 엔드포인트가 끊임없이 늘어납니다.

엔드포인트 Restful하게 즉 자원(data) 중심으로 만들어주셔야 합니다. View class명도 `ProductList`(상품 목록)으로 수정해주세요.

```suggestion
class ProductList(View):
```

2022-01-27 11:02 UTC, lordmyshepherd commented on products/views.py
> +            return JsonResponse({'message':'SUCCESS' ,'Limited Product List' : result ,'New Product List' : result2}, status=200)
위에서 설명드린 것과 마찬가지로, 'limited', '-created_at'과 같은 filtering 조건을 하드코딩 하지 않고,
client에서 filtering 조건을 input으로 받아서 유동적으로 상품정보를 반환할 수 있도록 해주세요.

힌트) result와 result2를 하나로 합쳐보세요~

2022-01-28 06:45 UTC, lordmyshepherd requested changes

2022-01-28 06:45 UTC, lordmyshepherd commented on products/views.py
> +                products = products.order_by("-created_at")
이부분도 client에서 동적으로 받아서 처리해주세요~

2022-01-28 07:47 UTC, aerialslash0422 commented on products/views.py
> +                products = products.order_by("-created_at")
```python
if sorting:
   products = products.order_by(sorting)
```

수정했습니다!

2022-01-28 09:14 UTC, lordmyshepherd requested changes

2022-01-28 09:14 UTC, lordmyshepherd commented on products/views.py
> +            sorting          = request.GET.get('sort', None)
default로 None을 넣게되면 Error가 발생하지 않나요?
```suggestion
            sorting          = request.GET.get('sort', 'id')
```

2022-01-28 09:14 UTC, lordmyshepherd commented on products/views.py
> +                products = products.order_by(sorting)
```suggestion
            products = Product.objects.filter(q).order_by(sorting)
```

2022-01-28 09:25 UTC, aerialslash0422 commented on products/views.py
> +            sorting          = request.GET.get('sort', None)
디폴트에 None 넣으니까 에러나서 제가 if sorting을 따로 뺐습니다.
수정했습니다

2022-01-30 13:09 UTC, merged